const types = {
    CREATE_TOKEN: 'CREATE_TOKEN',
    DELETE_TOKEN: 'DELETE_TOKEN',
    SET_INFO: 'SET_INFO',
    LOAD_LIST: 'LOAD_LIST',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    TOGGLE_SIDEBAR_SHOW: 'OGGLE_SIDEBAR_SHOW',
    TOGGLE_DEVICE: "TOGGLE_DEVICE",
    EXPAND_MENU: 'EXPAND_MENU',
    LOAD_MENU: 'LOAD_MENU',
    LOAD_CURRENT_MENU: 'LOAD_CURRENT_MENU',
    SWITCH_EFFECT: 'SWITCH_EFFECT',
    CURRENT_TAG: 'CURRENT_TAG',
    CURRENT_PAGE: 'CURRENT_PAGE'
}

export default types 